### ISSUE TITLE
403 Client Error

### ISSUE THREAD

**Issue by fablb** [lavaground/F1TV-Viewer#2]
Hi,

I wanted to use your script but when I get the master m3u8 in the clipboard and execute, I get the following error : `403 Client Error: Forbidden for url: ...`

Is it a new restriction by F1TV ?

Full error : 
```
[cli][info] Found matching plugin hls for URL https://f1tv-cdn-cent-live.formula1.com/ondemand/dc33/_C_/3/2/wif***/1/clip_2_master.m3u8?nva=***&ttl=***&cc=FR&token=****
error: Unable to open URL: https://f1tv-cdn-cent-live.formula1.com/ondemand/dc33/_C_/3/2/wif***/1/clip_2_master.m3u8?nva=***&ttl=***&cc=FR&token=*** (403 Client Error: Forbidden for url: https://f1tv-cdn-cent-live.formula1.com/ondemand/dc33/_C_/3/2/wif***/1/clip_2_master.m3u8?nva=***&ttl=***&cc=FR&token=****)
```

**Comment by lavaground** [comment]
Still works like a charm for me (Testing with Australia Race in 30 min 2019).
On older races i have to lower the resolution in the script-link as 1080p is not available.

How are you obtaining the m3u8 link?
What are you trying to watch?

Either:
- you don't have/are not using a valid subsciption 
- the link is already in use multiple times 

Or:
- got invalidated because you generated a new one in the meantime. 
- there could be other reasons, too, but those are the first ones that came to my mind...

The last one (invalidated) i managed to achive myself when testing the script and didn't pay attention.

P.S.: I think it would be wise to cut off/obfruscate some of the link in your comment, not sure how much can be used/abused.

**Comment by fablb** [comment]
> Still works like a charm for me (Testing with Australia Race in 30 min 2019).
> On older races i have to lower the resolution in the script-link as 1080p is not available.
> 
> How are you obtaining the m3u8 link?
> What are you trying to watch?
> 
> Either:
> 
> * you don't have/are not using a valid subsciption
> * the link is already in use multiple times
> 
> Or:
> 
> * got invalidated because you generated a new one in the meantime.
> * there could be other reasons, too, but those are the first ones that came to my mind...
> 
> The last one (invalidated) i managed to achive myself when testing the script and didn't pay attention.
> 
> P.S.: I think it would be wise to cut off/obfruscate some of the link in your comment, not sure how much can be used/abused.

I'm getting the link with network developper tools and search keyword 'master'.
I was trying to watch Germany 2019 full race.

I've got a F1 TV Access (in France).
I will try again with the one you just tried.

**Comment by fablb** [comment]
I tryed again and this time it's working fine, weird.
Anyway thanks for this script, do you know if there is a way to download a race with this link (not recording, I know VLC can) ?

**Comment by lavaground** [comment]
Hey @Fab-LBC 
Maybe it's the German GP 2019 which is broken, i'll check that later this evening.

Preventing to get too much attention, all i can say about your second question is: 
Take a look at CoCoCut or VLCs convert feature (dropdown at the "stream" button). :)

EDIT:
Just checked the German GP 2019, works for me. 
Only difference is "cc=DE" instead of "cc=FR" German/French subtitles i guess

**Comment by fablb** [comment]
> Hey @Fab-LBC
> Maybe it's the German GP 2019 which is broken, i'll check that later this evening.
> 
> Preventing to get too much attention, all i can say about your second question is:
> Take a look at CoCoCut or VLCs convert feature (dropdown at the "stream" button). :)
> 
> EDIT:
> Just checked the German GP 2019, works for me.
> Only difference is "cc=DE" instead of "cc=FR" German/French subtitles i guess

Thanks, and yeah it's working now for German GP.
Can't find anything about CoCoCut nevertheless.

**Comment by lavaground** [comment]
The Readme would be one way to find something about CocoCut or you can just go to https://cococut.net/ ;)
